# Generated by Django 3.0 on 2023-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toddoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='2020-10-11'),
            preserve_default=False,
        ),
    ]
